### ISSUE TITLE
time_summarise / ability to filter by periods and to have the ability to set start of period

### ISSUE THREAD

**Issue by JoeFernando** [business-science/tibbletime#15]
This is my second request:

In Australia our financial year starts 1/July to 30/June. Some large listed companies have financial year end in September. So to have the ability to set the start and end of financial years is useful.

It would also be super useful to have the ability to filter by "Q1" or "H1".

Background to my request:
I worked for a US listed company in Australia
All our reporting to the US was based on calendar years, so Q1 = Jan-Mar
When reporting to local regulatory bodies and for tender submissions we reported in Australian Financial year, so Q1 = Jul-Sep
Trying to organise the data in quarters/half-yearly for reporting between US and local requirements was a real nuisance and a lot time was spent checking to make sure the correct time periods were being reported.

Now if there was the ability to (1) define Financial year periods and (2) to search based on aggregates, such as Q1 life would have been oh so easy.

Is this something that you could consider building into the library.

Thanks in advance.
Kind regards,
Joe

**Comment by DavisVaughan** [comment]
I might be able to provide the ability to filter for words instead of formula dates. Such as filtering for "Q1" dates instead of `2013-01-01 ~ 2013-03-31`. I am not sure that I will be able to allow you to alter what "Q1" means. Meaning that Q1 would comply with US financial quarters of Jan-Mar and so on, and not with Australian. 

I might be able to allow you to define a start date for some date based operations. So maybe "start date is July 1st" then "do something every 3 months". This would align with Australian quarters.

I'm not sure yet. I'll do some more thinking.

**Comment by DavisVaughan** [comment]
@JoeFernando, if you can provide a full reproducible example here, I may have come up with a solution.

**Comment by DavisVaughan** [comment]
Generic period support should get you most of the way there. I do not have any current plans to support custom definitions for what Q1 looks like. I may support searching for specific financial periods such as Q1, but right now `time_filter` with specific dates should help.
