### ISSUE TITLE
time_summarise() Issue When Multiple Non-Index, Non-Numeric Columns

### ISSUE THREAD

**Issue by jarus-singh** [business-science/tibbletime#29]
Started playing around with tibbletime and love how easily I can manipulate data. I believe I've found a bug with how time_summarise() works. When I have a tbl_time object that has multiple non-index (e.g. day), non-numeric (e.g. open, close, high in stock data) columns, I don't get expected output. See the code snippet attached below.

**Comment by jarus-singh** [comment]
[time_summarise_issue.txt](https://github.com/business-science/tibbletime/files/1396775/time_summarise_issue.txt)

**Comment by DavisVaughan** [comment]
@jarus-singh thanks for playing around with the package! This is actually not a bug, but a design choice. tibbletime assumes that the dates are in ascending order for each group. This is why it works correctly when you group the data (each group has ascending order dates), but not when you don't (the date column alone is not in ascending order). It's really a speed thing, and also I don't want to arrange the data for the user because that feels wrong.

In the current release, no warning is issued with dates that aren't in ascending order, but the branch I am working on does warn the user.

```r
devtools::install_github('business-science/tibbletime', ref = 'feature-rcpp-is_ordered')
```

```r
> fb %>%
+   time_summarise(period = "m",
+                  sum_adj = sum(adjusted))
Note: Index not ordered. tibbletime assumes index is in ascending order. Results may not be as desired.
# A time tibble: 39 x 2
# Index: date
         date sum_adj
 *     <date>   <dbl>
 1 2013-02-28 1170.64
 2 2013-03-04 1226.14
 3 2013-04-24 1013.77
 4 2013-04-26 1011.26
 5 2013-06-24 1010.83
 6 2013-06-26 1112.23
 7 2013-08-26 2754.99
 8 2013-10-22 1884.62
 9 2013-10-28 2091.15
10 2013-12-24 4163.81
# ... with 29 more rows
```

If the user wanted to do what you suggested, with the results just being doubled per month and not using groups, just sort first.

```r
> fb %>% arrange(date) %>%
+     time_summarise(period = "m",
+                    sum_adj = sum(adjusted))
# A time tibble: 48 x 2
# Index: date
         date sum_adj
 *     <date>   <dbl>
 1 2013-01-31 1273.94
 2 2013-02-28 1067.34
 3 2013-03-28 1072.26
 4 2013-04-30 1170.76
 5 2013-05-31 1150.30
 6 2013-06-28  957.76
 7 2013-07-31 1228.10
 8 2013-08-30 1704.92
 9 2013-09-30 1830.48
10 2013-10-31 2323.54
# ... with 38 more rows
```

**Comment by jarus-singh** [comment]
Ah sounds good. I'll be sure to sort in the future if my df doesn't already have the index column sorted. Thanks for the clarification!
