### ISSUE TITLE
timesummarise with formula.tools loaded

### ISSUE THREAD

**Issue by chanelsf** [business-science/tibbletime#32]
Firstly, thanks for a great package.  

I just have an issue with `time_summarise` if a package of mine that imports `formula.tools` is loaded.

E.g. if I start with a clean session and run the following, it works:

```r
library(tibbletime)
data(FB)
FB <- as_tbl_time(FB, date)
```

# Calculate the mean and standard deviation of the adjusted column at a yearly interval

```r
FB %>%
  time_summarise(period = "yearly",
                 adj_mean = mean(adjusted),
                 adj_sd   = sd(adjusted))
```

However, if I add `library(formula.tools)` and then rerun the above, it throws an error.
It does not help to reload `library(tibbletime)` again.
Any idea why?

**Comment by DavisVaughan** [comment]
Hey @chanelsf, thanks for the kind words. The problem is that `formula.tools` implements its own `as.character.formula()` function. I'm using `as.character()` inside `time_summarise` with a formula argument, so the `formula.tools` version gets called. A quick way to get around this is to do:

``` r
library(tibbletime)
library(formula.tools)
# This line overrides the formula.tools as.character() method
# with the correct one for tibbletime
as.character.formula <- as.character.default

data(FB)
FB <- as_tbl_time(FB, date)

FB %>%
  time_summarise(period = "yearly",
                 adj_mean = mean(adjusted),
                 adj_sd   = sd(adjusted))

```

In the long term I plan on parsing the formula in a different way that wont use `as.character` but in the short term this may work for you
