### ISSUE TITLE
time_summarise gone?

### ISSUE THREAD

**Issue by jebyrnes** [business-science/tibbletime#39]
```

Error in function_list[[k]](value) : 
  could not find function "time_summarise"

```

**Comment by DavisVaughan** [comment]
Yes, `time_summarise()` has been removed, along with a number of other breaking changes.

See this [blog post](http://www.business-science.io/code%20tools/2018/01/04/tibbletime-0-1-0.html) and the [NEWS](https://business-science.github.io/tibbletime/news/index.html) for a complete list. 

You can likely replace `time_summarise()` with a combination of the new `collapse_index()` function and a `dplyr::group_by()` + `dplyr::summarise()` call. See the docs for `collapse_index()` for lots of examples.

If you have a specific problem let us know, otherwise I'm going to close this.

**Comment by jebyrnes** [comment]
Ah, didn't see it in the NEWS - thanks.
