### ISSUE TITLE
constraints on what can be rollified?

### ISSUE THREAD

**Issue by apsteinmetz** [business-science/tibbletime#43]
Loving rollify!  This is the real differentiating function of this package, IMHO.
Running into trouble trying to use the tidyquant/performance analytics functions with rollify, though.  Perhaps it just  a basic misunderstanding of mine.

```
library(tidyverse)
library(tibbletime)
library(tidyquant)

data("FANG")

#lets just say that GOOG is the reference asset we want to run a beta against.

wide_fang<-FANG %>% select(symbol,date,adjusted) %>% spread(symbol,adjusted)

wide_fang %>% tq_performance(Ra=AMZN,Rb=GOOG,performance_fun = CAPM.beta)
## A tibble: 1 x 1
#CAPM.beta.1
#*       <dbl>
#  1        1.35
```
The static function works.

Since the rolling beta function of performanceAnalytics is not implemented in tidyquant, we might want to hand rollify it.
```
#Lets rollify it on a one-month (20 trading days) window.

#This fails
beta_roll_20<-rollify(~tq_performance(.Ra,.Rb,performance_fun=CAPM.beta),window = 20)

betas <-wide_fang %>% mutate(beta=beta_roll_20(AMZN,GOOG))
#Error in mutate_impl(.data, dots) : 
#Evaluation error: object '.Ra' not found.

#This works.
beta_roll_20<-rollify(~lm(.x ~ .y)[[1]][[2]], window = 20)

betas <-wide_fang %>% mutate(beta=beta_roll_20(AMZN,GOOG))

```

**Comment by DavisVaughan** [comment]
Glad you're liking `rollify()`! That's one of my favorites as well. There are two problems with your setup:

1) `tq_performance()` has a first argument, `data`, that you are not specifying. It has to be a `tibble`, which makes things frustrating because `mutate` will only pass the two individual _vectors_ `AMZN` and `GOOG` to the rollified function. 

2) `tq_performance()` returns another tibble, which is probably not what you want as your end result (you'd get a `beta` column of your `betas` tibble full of more tibbles, with each one containing 1 value, the Beta for that rolling period. Its the "list column" idea if you are familiar.)

You can make it work, but it's kind of ugly and _really_ slow. Lot's of conversion happening. Notice that we have to pass the date column in as well, and we are using the `..1`, `..2`, `..3` syntax from `purrr` to make it work.

```r
beta_roll_20 <- rollify(
  .f = ~{
    .data <- tibble(date = ..1, .Ra = ..2, .Rb = ..3)
    tq_performance(data = .data, Ra = .Ra, Rb = .Rb, performance_fun = CAPM.beta)$CAPM.beta.1[1]
  }, 
  window = 20, 
  unlist = TRUE
)

betas <- wide_fang %>%
  mutate(beta = beta_roll_20(date, AMZN, GOOG))
```

In this case, I'd go for the more performant version with just xts and PerformanceAnalytics. At each roll, it forms two xts objects (Ra and Rb) and passes them into `CAPM.beta()`. 

```r
beta_roll_20 <- rollify(
  .f = ~{
    Ra <- xts(x = ..2, order.by = ..1)
    Rb <- xts(x = ..3, order.by = ..1)
    CAPM.beta(Ra, Rb)
  }, 
  window = 20
)

betas <- wide_fang %>%
  mutate(beta = beta_roll_20(date, AMZN, GOOG))
```

In general, complicated functions like `tq_performance()` that accept tibbles and return tibbles aren't really made for these kind of rolling calculations. I definitely see the value in having rolling Beta calculations though, and am keeping things like this in mind as I work on some financial extensions of `tibbletime`.

**Comment by DavisVaughan** [comment]
Finally, if I were you, to squeeze out the most performance I would roll my own function just like what you were trying to do at the end of your comment.

This is essentially what `CAPM.beta()` does anyways, but even they have some additional slowdown with conversion of xts to data.frame and back, so this is faster.

```r
beta <- function(Ra, Rb) {
  lm(Ra ~ Rb) %>%
    coef() %>%
    pluck(2)
}

beta_roll_20 <- rollify(beta, window = 20)

betas <- wide_fang %>%
  mutate(beta = beta_roll_20(AMZN, GOOG))
```

**Comment by apsteinmetz** [comment]
Great insight. Thanks.  tidyquant is a great effort at putting wrappers around functions that expect xts objects but it's an intermediate step on a journey that ends with all-tidy equivalent functions for finance.  tibbletime and lubridate will really facilitate that.  Thanks!
