### ISSUE TITLE
variable period enhancement

### ISSUE THREAD

**Issue by ldecicco-USGS** [business-science/tibbletime#9]
This is *sooo close* to what I need. Any future work planned to let the user define the period? Currently, I need a 6 hour window.

**Comment by DavisVaughan** [comment]
Hey @ldecicco-USGS. I thought of this myself while making the initial version. Yes, I think arbitrary periods are the way to go, glad to know others want this feature. It will take a bit of rewriting, but I have some ideas on how to do it!

I'll leave this post open as a marker

**Comment by DavisVaughan** [comment]
@ldecicco-USGS, I was thinking about this, and had a quick question.

For your 6 hour window, would you rather the window start from hour 0 in that day, or from the first data point in your data set? Meaning:

Either the day is sliced into:
0, 6, 12, 18, 24 

Or if your first data point was at (for example) 2017-01-01 10:12:14, the time is sliced like this:
2017-01-01 hour 10
2017-01-01 hour 16
2017-01-01 hour 22
2017-01-02 hour 4
...

I'm not sure if one makes more sense than the other, or if both cases have their uses. What did you need for your problem? A specific example might be useful for me.

**Comment by lbusett** [comment]
Jumping in here: I'd say common use cases coming into mind (e.g., computing average of  a meteo parameter over "standard periods)" would call for the first option (0, 6, 12, 18, 24). The other possibility seems a bit "erratic" to me, since its outcomes would depend on the timing of the first observation, which could be random (e.g., imagine wanting to average/cumulate rainfall data from multiple pluviometer sensors over  common timestamps: dividing using the starting point in time could lead to "decoupling" of the aggregated time series depending on the time at which the different sensors started recording).

HTH, and thanks for an interesting package !

**Comment by DavisVaughan** [comment]
@lbusett, thanks for the input. It's definitely helpful. This is what I am thinking it should do as well. I believe `xts` uses a similar idea for its `apply.daily` style functions. 

With that in mind, I _think_ that I can implement both, and allow the user to have a toggle that specifies which to use. The default would be the "standard periods."

Generic periods would be pretty slick because `xts` only has the ability to easily apply to daily, monthly, weekly, yearly, and quarterly. Even with that, you only apply at 1 period at a time (It doesnt look like you can easily do, say, every 2 days).

**Comment by lbusett** [comment]
Even better would be to be able to set both the periodicity and a specific moment to start "counting" (e.g.,  summarize over 4 months, starting 21/12). My 2 cents: a "simple" way to do so could be to create a dummy grouping variable "on the fly" based on the selections of the user and the date/time variable, and then aggregate on that using standard aggregation functions.

**Comment by DavisVaughan** [comment]
@lbusett, great minds think alike. I think that this is going to be the plan going forward. It just came up over in #15 as well as a solution to doing analysis "by quarter" where the starting quarter changes depending on the country you live in. Thanks for the input!

**Comment by lbusett** [comment]
You're welcome.  Indeed, that functionality would be helpful for a package I'm currently developing, so it's win-win.

**Comment by DavisVaughan** [comment]
@ldecicco-USGS and @lbusett, I've just pushed a new update to Github with support for generic periods. Install using

```r
devtools::install_github(business-science/tibbletime)
```

And check out the `as_period` documentation as well as `time_group`. 

`time_summarise` is not yet supported for this but it will be.

You should be able to do something like:

```r
data(FB)

FB <- as_tbl_time(FB, date)

as_period(FB, 6~d)
```

For the 6 hour times, switch out `6~d` for `6~h`. The `start_date` argument can provide added customization if needed.

**Comment by lbusett** [comment]
Ok, great ! Will have a look when possible !

**Comment by DavisVaughan** [comment]
Closing this as this problem seems to be mostly solved with generic period support. There is more work to do (business days, holidays, all kinds of niche thing), but for this issue I think the support is there.
